### ISSUE TITLE
Compilation Instructions and Dependencies.

### ISSUE THREAD

**Issue by oshaboy** [increpare/gestalt_31#1]
I am trying to compile it but nowhere does it say what dependencies does it require and how to compile it.

**Comment by increpare** [comment]
Hello :) It's made with the Haxegon engine.  Instructions for compiling haxegon games can be found here : 

http://www.haxegon.com .

**Comment by oshaboy** [comment]
I keep getting an error at line 2684 saying "characters 54-56 : unexpected ->"

**Comment by increpare** [comment]
Hm, spooky.  Can't reproduce this error here.  Knowing some other things might help:

1: Could you tell me what version of haxe you have installed ("haxe --version")
2: Info about what libraries you have installed "haxelib list"
3: What platform you're compiling for (HTML5/binary/etc)
4: What your OS is (including what version)
5: have you tried any things to fix it?  (Like replacing/rewriting the lambda function)

Best :)

S

**Comment by oshaboy** [comment]
1. The "haxe --version" command doesn't exist but I can tell you it is 3.4.7

2. I have haxegon 0.13.0, lime 7.5.0 and openfl 8.9.1

3. HTML5

4. Windows 10 Version 1809 OS Build 17763.557. I have a Linux Distro installed. I will try to compile it on it. 

5. I don't know haxe. So I don't know to do it.

**Comment by oshaboy** [comment]
Nope. Antergos gives the same error both rooted and unrooted

**Comment by increpare** [comment]
I'm using Haxe 4 it seems, so that might be the problem. Or it might not.  You could try upgrading.  


OR, just for comparison, you might want to try compiling one of these (other games made with haxegon), see if they work:

https://github.com/increpare/gestalt_OS 
https://github.com/increpare/W-rfelreparaturger-t
